### ISSUE TITLE
Arrow key camera control

### ISSUE THREAD

**Issue by vanpeltm1785** [counteragent/KH-Camera-Control#1]
Hello, when controlling my camera with this application, the arrow keys don't seem to consistently move the camera.  If I tap the arrow keys, it moves too slow, but if I hold in the arrow keys, it moves very erratically.

Any suggestions?

I've tried different speeds in the settings, but that didn't seem to help.

**Comment by counteragent** [comment]
This is a limitation of the camera and the way we have to interface with it through urls over the network.

The best thing to do is just take the time to set all your presets and not bother with micro adjustments after that. The only way I know of to get better, more precise control is to actually use a hardware camera control.

**Comment by vanpeltm1785** [comment]
Thanks,

Have you checked out the iOS app PanTiltZoom? They are doing it with a software joystick somehow, and it seems to go pretty smoothly.

**Comment by counteragent** [comment]
It appears they're using a different protocol (VISCA) to communicate to the camera. Not sure if this is why it works better or not. This app is using the basic HTTP CGI protocol to communicate with the camera.

Also, it's a paid app, so there's that.

**Comment by vanpeltm1785** [comment]
Ha, very true. Thanks for the quick responses!
